### ISSUE TITLE
Implement lifecycle policies

### ISSUE THREAD

**Issue by roma-glushko** [roma-glushko/broom#1]
Example of the lifecycle config:

```yaml
name: "Clean desktop screenshots"
dir: "/home/roma/Desktop/"
action: 
  type: "move_to_trash"  # e.g. delete_permanently
conditions:
  - X
  - B  
```
